### ISSUE TITLE
Icon picker

### ISSUE THREAD

**Issue by adesmet** [danawoodman/react-fontawesome#11]
Nice work! I think an icon picker would be a fine addition to this library (like this one: http://mjolnic.com/fontawesome-iconpicker/)

**Comment by adesmet** [comment]
Well if I'm not mistaken, your library allows me to display icons (and do some manipulations like rotate). But for a project I'm doing now, I could use an icon picker: a sort of autocomplete component that lets you type in a keyword and display the list of icons matching it. Sort of like a form input, but for icons. Does that make sense?

**Comment by danawoodman** [comment]
Yeah, I understand what you're proposing. However, this library is just mean to display a single Font Awesome icon. Perhaps a separate library that uses this library would make sense though

**Comment by danawoodman** [comment]
Closing but would love to see `react-fontawesome` used in such a library @adesmet 😁
