### ISSUE TITLE
changelog v1

### ISSUE THREAD

**Issue by jonathanong** [danawoodman/react-fontawesome#12]
don't see any breaking changes for v1 from the git commit log but would be nice if you updated https://github.com/danawoodman/react-fontawesome/blob/master/changelog.md

thanks!

**Comment by danawoodman** [comment]
@jonathanong you're correct, no breaking changes. I just wanted to indicate on NPM that this is considered "production ready". Sorry for any confusion! I'll update the changelog (forgot to do that!) 👍

**Comment by danawoodman** [comment]
Resolved, thanks for reporting @jonathanong!
