### ISSUE TITLE
What's the differences with react-fa?

### ISSUE THREAD

**Issue by andreypopp** [danawoodman/react-fontawesome#14]
https://github.com/andreypopp/react-fa

**Comment by danawoodman** [comment]
Hey @andreypopp! I actually was inspired by your project when I started this one. The main difference as I see it is react-fontawesome does not require any dependencies, especially the WebPack dependency. I initially couldn't use WebPack on a particular project and wanted something similar to what you created. I now use WebPack heavily but I still like not having the component import it's own version of font-awesome CSS which is stuck a particular version range. I think your project is awesome tho!

**Comment by andreypopp** [comment]
Well, you always could use `react-fa` without webpack: `import Icon from 'react-fa/lib/Icon'` and that's it. I'm just don't see the reason to create an identical package, even without first approaching the authors of already existent alternative to describe a use-case which differs slightly from the original one.

**Comment by danawoodman** [comment]
@andreypopp this isn't obvious when using your project as it's not documented anywhere but in retrospect I could have contacted you about the matter. I don't see a major issue with having other choices out there but I understand your perspective.
