### ISSUE TITLE
Icons don't display

### ISSUE THREAD

**Issue by timfpark** [danawoodman/react-fontawesome#16]
In my hands, after doing an install with:

    npm install --save react-fontawesome

I am not able to see any icons by including something like this in one of my views:

    <FontAwesome name='bars' />

unless I also include Font Awesome's CDN .js in the <head> tag, ala:

    <script src="https://use.fontawesome.com/3bd7769ce1.js"></script>

Are there any other installation steps required beyond the npm package?  Or is this a bug?

I'm using React 0.15 with react-fontawesome 1.1.0.

**Comment by danawoodman** [comment]
On first look, I would assume that you're not including the CSS?

I'll have a look at this in more detail later today too

**Comment by timfpark** [comment]
That's right - it sounds like what I am doing then is actually the right way of going about it (for the CDN based approach) - if so go ahead and close this out.

**Comment by danawoodman** [comment]
@timfpark I'm not familiar with the FA javascript CDN but you could use this one instead: https://www.bootstrapcdn.com/fontawesome/

**Comment by timfpark** [comment]
Thanks @danawoodman!

**Comment by danawoodman** [comment]
@timfpark you're welcome 👍

**Comment by novotnej** [comment]
It would be nice if you could add this information to the readme, so that fewer of us have to waste time figuring it out? 

Cheers

**Comment by danawoodman** [comment]
@novotnej this information is in the readme: 

![](https://cl.ly/kSXs/Screen%20Shot%202017-05-15%20at%201.23.21%20PM.png)

If you think it should be elsewhere I would accept a PR for it

**Comment by novotnej** [comment]
My apologies, didn't notice it there. I created a PR where I moved it to the install section, I think it should rather be there than at the end of features..

**Comment by danawoodman** [comment]
That's a better spot for it, thanks!
