### ISSUE TITLE
Consider using aria?

### ISSUE THREAD

**Issue by Phyks** [danawoodman/react-fontawesome#20]
Hi,

Would be awesome if [accessibility features](http://fontawesome.io/accessibility/) were wrapped as well. That is using `aria-hidden=true` and providing a `prop` to pass an alternate text to put either in an `aria-label` or a hidden `<span>`.

Thanks!

EDIT: I can make a PR for this if you are ok for a review and eventual merge.

**Comment by danawoodman** [comment]
@Phyks yeah that would be great, PR totally welcome! 👍

**Comment by Phyks** [comment]
Sorry, I got really busy lately and missed this one :/ Here is a PR :)
