### ISSUE TITLE
Best way to handle color change on hover?

### ISSUE THREAD

**Issue by acomito** [danawoodman/react-fontawesome#23]
I tried adding a class with css hover effects, but didn't seem to work. Is there another way?

**Comment by danawoodman** [comment]
@acomito what does the CSS look like? Something like this?:

```css
.my-class:hover { color: red; }
```

Note to color Font Awesome you need to use `color` and that the hover should be directly applied to the class since it just returns a `<span>`

**Comment by danawoodman** [comment]
@acomito what did you do to get it to work for other people that may have the issue?

**Comment by acomito** [comment]
I'm using aphrodite for inline/js css and hover is working just as expected.
