### ISSUE TITLE
Adds two fa-fa class ?

### ISSUE THREAD

**Issue by bboysathish** [danawoodman/react-fontawesome#26]
Hi,

This is happening recently where the font-awesome icons are displayed as flag, while i inspect i see react-fontawesome adds two more fa-fa class.

Details below,
1. Inspected tag
   ![inspected_code](https://cloud.githubusercontent.com/assets/8023447/19043485/f3e48730-89ad-11e6-9629-9bc83a75859e.png)
2. Actual Code
   ![inspect](https://cloud.githubusercontent.com/assets/8023447/19043495/fc0fc3de-89ad-11e6-8406-62de339fb105.png)
3. Shrinkwrap React Fontawesome version
   ![shrinkwrap-font-awesome](https://cloud.githubusercontent.com/assets/8023447/19043506/0858332e-89ae-11e6-86e2-66118e2e6891.png)
4. Package.json version
   ![react-shrinkwrap](https://cloud.githubusercontent.com/assets/8023447/19043511/1004ba5c-89ae-11e6-817e-1b412d30ff93.png)

**Comment by bboysathish** [comment]
@danawoodman  Any updates on this ?

**Comment by zhuangya** [comment]
i think you should only write `<Fa name="download" />`

**Comment by bboysathish** [comment]
@zhuangya Previously it was working.. when it is changed ??

**Comment by danawoodman** [comment]
@bboysathish I haven't changed that functionality, did `<Fa name='download' />` not result in `fa fa-download`?

**Comment by danawoodman** [comment]
Closing, please re-open if still  an issue @bboysathish
