### ISSUE TITLE
How do I use this exactly?

### ISSUE THREAD

**Issue by amihaiemil** [danawoodman/react-fontawesome#27]
Hello,

I have trouble getting this to work (I'm new to react so probably I'm missing something obvious).
I installed the lib via npm, declared in package.json and imported in my react class, like this:

![image](https://cloud.githubusercontent.com/assets/6305156/19729373/7372cc02-9b9f-11e6-8482-aff9a483f650.png)

The render method this:

![image](https://cloud.githubusercontent.com/assets/6305156/19729391/813410b2-9b9f-11e6-95e7-e6d31781c772.png)

The code compiles, my other elements render, but I see no icon rendered on the page.
Any help would be appreciated.

Best regards,
Mihai

**Comment by Casy** [comment]
just add this:
@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css');

**Comment by JuHwon** [comment]
is there any better solution?

**Comment by danawoodman** [comment]
@amihaiemil @JuHwon this repo does not include the FontAwesome assets so you must include them yourself (this is mentioned in the readme). There are many options to do this including using WebPack or just directly linking to them in your page (using CDN or local files, whatever you work)

**Comment by danawoodman** [comment]
Thanks @Casy for mentioning one option for people

**Comment by mhaligowski** [comment]
Any idea how to make it work with npm? I'm using the create-react-app, and was able to use Bootstrap like a charm: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-bootstrap.

React-fontawesome is super close to that, bot not sure how I can make it work with `fontawesome` package in NPM.

**Comment by danawoodman** [comment]
@mhaligowski you can install it using `npm install -S react-fontawesome` and then, depending on what your build process is, you will need to include Font Awesome's CSS files. You can use the [CDN version](https://www.bootstrapcdn.com/fontawesome/) or if you're using something like Webpack you can `npm i -S font-awesome` and then in your CSS/SCSS file you can `@import '~font-awesome/scss/font-awesome` or similar. Hope that helps!
