### ISSUE TITLE
Icon names do not match website

### ISSUE THREAD

**Issue by cainaleaouk** [danawoodman/react-fontawesome#29]
Hi there,

I've been trying to use your component, which is working beautifully. Thanks for that.

My problem is, I have to guess 1000 the name of the icon until I get it right, could they match the naming in the font-awesome website? If not, where can I get a list of names and icons? This guessing game is taking way too much development time from me.

Cheers,
Cai

**Comment by danawoodman** [comment]
The names should just be the font awesome name minus the `fa-` prefix, does that not work?

**Comment by danawoodman** [comment]
Closing, lemme know if you still think this is an issue @cainaleaouk

**Comment by cainaleaouk** [comment]
Yep seemed to work, thanks!
