### ISSUE TITLE
'icon-' prefix?

### ISSUE THREAD

**Issue by gthomas-appfolio** [danawoodman/react-fontawesome#31]
Have an issue with some legacy CSS that uses the older FontAwesome 3.x names for icons: `icon icon-*` etc.

Aside from forking the component, is there a way to easily config or extend this component to use the 'icon' in place of 'fa'?

**Comment by danawoodman** [comment]
Not at this point but a PR would be very welcome to add this

**Comment by gthomas-appfolio** [comment]
Thanks, no problem.   I'll try and send a PR this week

**Comment by danawoodman** [comment]
Thanks @gthomas-appfolio, closing this in preparation for your PR
