### ISSUE TITLE
1.4.0 breaks everything in our Material-UI project

### ISSUE THREAD

**Issue by bushmango** [danawoodman/react-fontawesome#32]
More details if we figure anything else out -- just verified that updating this package is what breaks our project:

 Update "react-fontawesome" in package.json from 1.3.1 to 1.4.0? Yes

**Comment by danawoodman** [comment]
@bushmango hmm that is weird. Please let me know what errors you are seeing so I can help

**Comment by bushmango** [comment]
The error I get is:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AppTitleBar`.

**Comment by bushmango** [comment]
It happens in any component with <FontAwesome /> in it

**Comment by bushmango** [comment]
Here's our (non-private) dependencies. Notice react 15.3.2
"dependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "bind-decorator": "^1.0.10",
    "chalk": "^1.1.3",
    "copyfiles": "^1.0.0",
    "figlet": "^1.2.0",
    "freezer-js": "^0.11.2",
    "lockr": "^0.8.4",
    "lodash": "^4.17.2",
    "material-ui": "0.16.2",
    "moment": "^2.16.0",
    "numeral": "^1.5.3",
    "react": "15.3.2",
    "react-dom": "15.3.2",
    "react-fontawesome": "1.4.0",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-motion": "^0.4.5",
    "react-router": "^3.0.0",
    "react-tap-event-plugin": "^1.0.0",
    "superagent": "^2.3.0",
    "tslint": "^3.15.1",
    "tslint-react": "^1.1.0",
    "typescript": "^2.1.1",
    "webpack": "^2.1.0-beta.25",
    "xml2js": "^0.4.17"
  },
  "devDependencies": {
    "source-map-loader": "^0.1.5",
    "ts-loader": "^1.2.1"
  }

**Comment by KagamiChan** [comment]
It seems that as 09f7c01d70eeed1b9d9796a97dcd364abf503dd0 adds another export, which prevents add-module-exports from working, as the module takes effect if only the export default declaration exists

**Comment by danawoodman** [comment]
@KagamiChan interesting, thanks for observation. Any thoughts on a workaround?

@bushmango for now I would downgrade reat-fontawesome until we fix this

**Comment by KagamiChan** [comment]
If I understand correctly that PR, the exported srOnlyStyle is for test purpose, so maybe we can create a file for this piece of code and require it both in `index.js` and `test.js`. This won't add extra labor for maintaining srOnlyStyle, but might leave some difficulty for those who want to customize the style.

btw. using `import` statement won't be influenced by this PR, only `require` will.

**Comment by danawoodman** [comment]
Makes sense, I will try and push up a fix unless you beat me to it @KagamiChan 😄

**Comment by KagamiChan** [comment]
I would like to help given some time. But I feel this issue somewhat urgent because there's risks that it dose not expose until codes get compiled and shipped to users, which did happen for our project.

**Comment by danawoodman** [comment]
I'll try to get to it today

**Comment by vsaarinen** [comment]
This also caused our product to break, and required quite a bit of detective work to narrow down the cause. Downgrading to 1.3.1 fixed the problem.

**Comment by danawoodman** [comment]
Sorry for delay, finally got a a chance to fix this. New release is `v1.5.0`. Can someone try it out and report back? @vsaarinen @KagamiChan @bushmango

**Comment by getreup** [comment]
I had the same problem and this version fixed it for me.

**Comment by danawoodman** [comment]
Thanks for the confirmation @getreup!
