### ISSUE TITLE
Problem stacking icons

### ISSUE THREAD

**Issue by cannin** [danawoodman/react-fontawesome#35]
From the Font Awesome examples: http://fontawesome.io/examples/

    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-flag fa-stack-1x fa-inverse"></i>
    </span>

this does not seem to work:

    <FontAwesome name='stack' size='lg'>
      <FontAwesome name='circle' stack='2x' tag="i" />
      <FontAwesome name='flag' inverse stack='1x' tag="i" />
    </FontAwesome>

The returned element is: 

    <span aria-hidden="true" class="fa fa-stack fa-lg"></span>

Is this a bug or am I doing something wrong?

**Comment by danawoodman** [comment]
This library doesnt (yet) have a stack wrapper, so you need to do this instead:

```jsx
<span class='fa-stack fa-lg'>
  <FontAwesome name='circle' stack='2x' tag="i" />
  <FontAwesome name='flag' inverse stack='1x' tag="i" />
</span>
```

**Comment by danawoodman** [comment]
PR welcome to add that wrapper tho...
