### ISSUE TITLE
Stacked Icons

### ISSUE THREAD

**Issue by chrisdebug** [danawoodman/react-fontawesome#36]
How do you do stacked icons?

**Comment by danawoodman** [comment]
@chrisdebug right now you have to wrap your icons in a span like:

```js
<span className='fa-stack fa-lg'>
  <FA name='square-o' stack='2x' />
  <FA name='twitter' stack='1x' />
</span>
```

I added an example to the `examples` directory to demonstrate this: https://github.com/danawoodman/react-fontawesome/blob/master/examples/index.js#L11

I'm welcome to a PR that exports a wrapper component for this if you're looking for something to do 😉

**Comment by chrisdebug** [comment]
Thanks @danawoodman! I'm pretty busy but if I get any time, I might.
