### ISSUE TITLE
Unknown prop on <span> tag

### ISSUE THREAD

**Issue by demands** [danawoodman/react-fontawesome#37]
Hello! Thanks for this module, it's great! I have just one minor issue, which is that if I use any of the special params like `spin`, `stack`, `pulse`, etc, I get the following warning in my browser console:

```js
<FontAwesome name='cutlery' spin />
```

```
Warning: Unknown prop `spin` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by FontAwesome)
    in FontAwesome (created by xyz)
```

I can work around this by doing the following:

```js
<FontAwesome name='cutlery' className='fa-spin' />
```

...but that's a bummer, since the nicer syntax is half the reason to use this module. Seems like you could solve this by stripping all non-HTML-friendly properties from the provided ones before passing along to the tag. Thoughts?

**Comment by danawoodman** [comment]
@demands that's strange... shouldn't be the case. Let me investigate.

**Comment by danawoodman** [comment]
@demands it works for me. Have a look at the `examples` directory and see if you might be missing something in your setup.

![](https://cl.ly/jAj8/Screen%20Recording%202017-02-14%20at%2009.56%20AM.gif)

**Comment by ashnur** [comment]
Same issue for me.
