### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by ahmadsholehin** [danawoodman/react-fontawesome#42]
Getting warnings:

> Warning: FontAwesome: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by danawoodman** [comment]
Thanks @ahmadsholehin, closing this in favor of the PR that should solve this #41
