### ISSUE TITLE
No Icons showing

### ISSUE THREAD

**Issue by goreRatzete** [danawoodman/react-fontawesome#44]
Hi I just tried this out and couldn't make it work.

I used the following code:
```
import React, {PropTypes} from "react";
import FontAwesome from "react-fontawesome"

<span><FontAwesome name="briefcase"/>Working Specialty</span>
```

This is what gets rendered: 
```
<span>
    <span aria-hidden="true" class="fa fa-briefcase"></span>
    <!-- react-text: 41 -->Working Specialty<!-- /react-text -->
</span>
```

Am I missing something? No Icon shows up.

**Comment by danawoodman** [comment]
Did you include the FontAwesome font in your project somewhere?

**Comment by goreRatzete** [comment]
Yes I used npm i and imported it via webpack.

**Comment by danawoodman** [comment]
If you inspect it in the browser what do you see? Can you look in developers tools and see the assets loading for the FontAwesome fonts?

**Comment by je553** [comment]
I had this same issue, but after adding a `<link />` to the fontawesome stylesheet to my main html app container, it worked fine. Let me know if this works for you!

**Comment by danawoodman** [comment]
@je553 yeah, this React component does not include the CSS or fonts so that is to be expected 😄 

Closing as I assume that was the issue

**Comment by huyle2607** [comment]
I just tried and all you need to do is to include the FontAwesome stylesheet into your index.html file. Thanks for your help @je553

**Comment by wizzfizz94** [comment]
Is this part of the readme or on the npm page anywhere? Seems like an important stepup step that isn't addressed in docs.

**Comment by danawoodman** [comment]
@wizzfizz94 yes, this is right below the install section of the README:

![](https://cl.ly/rZVA/Screen%20Shot%202018-05-14%20at%208.11.24%20PM.png)

**Comment by wizzfizz94** [comment]
oh silly me :man_facepalming: 
Any recommended guides on configuring a local version with css and fonts locally?
