### ISSUE TITLE
React v15.5.0 createClass warning.

### ISSUE THREAD

**Issue by gabrielrtakeda** [danawoodman/react-fontawesome#45]
# Description
When running my personal project, this warning is dispatching:

```
Warning: FontAwesome: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

I am googled a bit and I found the [React v15.5.0 blog post](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass).

Basically, is need to make this:

```patch
-import React, { Component, PropTypes } from 'react'
+import PropTypes from 'prop-types';
+import React, { Component } from 'react';
```

It has the [React-PropTypes-to-prop-types](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) codemods but, it seems that does not migrate the PropTypes of stateless components.

To install the codemods, follow the following steps:

1. `npm install -g jscodeshift`
1. `git clone https://github.com/reactjs/react-codemod.git` (inside the root of the project)
1. `cd react-codemod  && npm install`

To run the migration is:
- `jscodeshift -t react-codemod/transforms/class.js <path>`
As described in [Migrating from React.createClass](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) section.

**Comment by danawoodman** [comment]
What version of `react-fontawesome` are you using?

**Comment by danawoodman** [comment]
If you are not on `v1.6.0` or above, please upgrade as that issue should have been fixed already.

**Comment by gabrielrtakeda** [comment]
Hi, @danawoodman I am using the v1.5.0, thanks for the quick reply and, sorry for the inconvenience.

**Comment by danawoodman** [comment]
No worries, glad you sorted it out!
