### ISSUE TITLE
Font Awesome 4.7

### ISSUE THREAD

**Issue by Ideki** [danawoodman/react-fontawesome#48]
Hi,
Will you update to font Awesome 4.7 which was release in April?
if so, when do you expect to have it ready ?
Thank your for your Awesome work. :)

**Comment by danawoodman** [comment]
@Ideki have you tried react-fontawesome with FA 4.7? Did you notice anything not working? Things should just work... You have to install FA font outside of react-fontawesome so you can upgrade whenever you want

**Comment by danawoodman** [comment]
Reopen if you have specific bugs to report 😄
