### ISSUE TITLE
Seems to require css file

### ISSUE THREAD

**Issue by jbernard1** [danawoodman/react-fontawesome#52]
I had the impression that we wouldn't need to depend on a css file however without it nothing gets rendered on my component.

**Comment by avastamin** [comment]
https://github.com/danawoodman/react-fontawesome/issues/44

**Comment by danawoodman** [comment]
This would require the use of a build tool like webpack to bundle the CSS and fonts in that case which this project has no intent to require on end users. You can use the CDN version or use webpack or similar in our project. Readme explains how to do this. Thanks for understanding 👍
