### ISSUE TITLE
Spin counter-clockwise

### ISSUE THREAD

**Issue by nhpace** [danawoodman/react-fontawesome#55]
I believe spin spins the icon in a clockwise manner. Any option to spin counter-clockwise?

**Comment by danawoodman** [comment]
@nhpace I don't think Font Awesome supports that, see [here](http://fontawesome.io/examples/#animated). If they do, let me know and I will reopen!

**Comment by nhpace** [comment]
https://github.com/FortAwesome/Font-Awesome/pull/3749

**Comment by danawoodman** [comment]
@nhpace unless FA supports it natively I don't plan to add it since I'm trying to stay 1:1 with their API. Hope you understand! You can always add a `className` with whatever animations you want tho!

**Comment by nhpace** [comment]
Thanks, that was my plan B! :)
