### ISSUE TITLE
How to use the cssModule prop?

### ISSUE THREAD

**Issue by rvmourik** [danawoodman/react-fontawesome#56]
Hi There,

Can't seem to figure out how to get this working with css modules, can you give me some more info then there is already on the api docs page?

Regards,

Robbert

**Comment by danawoodman** [comment]
@rvmourik Maybe this will help?:
https://github.com/danawoodman/react-fontawesome/pull/21#issuecomment-240645234

If you figure it out I would love a PR to add in some docs on this as I don't use it myself

**Comment by rvmourik** [comment]
Hi

Created an issue and created a pull request

Robbert
