### ISSUE TITLE
Font Awesome 5 compatibility

### ISSUE THREAD

**Issue by fabriceci** [danawoodman/react-fontawesome#63]
Font Awesome 5 is out and change a bit the class names.

**Comment by danawoodman** [comment]
This will require a bit of change to the API but a proposal or PR is welcome

**Comment by frinyvonnick** [comment]
@danawoodman is someone working on this issue ? If not i'll do it 😄

**Comment by danawoodman** [comment]
@frinyvonnick go for it! Keep in mind that Font Awesome already has their own React component for v5 now

**Comment by frinyvonnick** [comment]
Oh didn't know it 😕. You are referring to this repository https://github.com/FortAwesome/react-fontawesome ? I'll study this one and if it doesn't fit my needs I will make a pull request. Thanks for the information 👍

**Comment by danawoodman** [comment]
Exactly. Unless `react-fontawesome` does things the official one doesn't do, I would say go with the official. If you do end up wanting to do a PR, I think we could accomplish it by adding some boolean properties:

```jsx
<FA name="rocket" solid />
<FA name="rocket" regular />
<FA name="rocket" light />
```

**Comment by danawoodman** [comment]
Re-open if you think you'll do a PR!
