### ISSUE TITLE
icon does not change with state change

### ISSUE THREAD

**Issue by rheinheimer** [danawoodman/react-fontawesome#65]
I have very basic icon: a folder that should open or close depending on whether or not the item is active. My code looks like `<FontAwesome className="fal fa-lg" name={this.props.active ? "folder-open" : "folder"}/>` This results in the correct icon being rendered the first time, but when another item is activated, the icons do not change.

**Comment by rheinheimer** [comment]
Quick followup: This is not the right library to use. For FA5: https://github.com/FortAwesome/react-fontawesome

**Comment by danawoodman** [comment]
Yes, use the official library for Fa 5. Please note you can pass `size=“lg”` instead of class names.
