### ISSUE TITLE
Got error when npm run test.

### ISSUE THREAD

**Issue by kmvan** [danawoodman/react-fontawesome#67]
``` 
 1) react-fontawesome
       "before all" hook:
     TypeError: require(...).env is not a function
      at Context.<anonymous> (node_modules\mocha-jsdom\index.js:52:22)
```

Anybody tried?

**Comment by danawoodman** [comment]
@kmvan you mean when checking out the git repo and running the tests? Or do you mean in your own test suite?

I'm not aware of any issue with the repository tests failing.

PS sorry for the super long delay in reply!!

**Comment by danawoodman** [comment]
Closing till I get more details on how to reproduce
