### ISSUE TITLE
Please update to Font-Awesome 5

### ISSUE THREAD

**Issue by tashburn** [danawoodman/react-fontawesome#69]

**Comment by santosguilherme** [comment]
+1

**Comment by danawoodman** [comment]
Please use the official font awesome React component for v5. 

https://github.com/FortAwesome/react-fontawesome

Reopen if something in React-fontawesome exists that the official component misses.

**Comment by KagamiChan** [comment]
Our project is using this package everywhere and migration will be too time consuming to take place for now. So I'm working on a compatible version, including:
- using shims taking from official v4-shim (MIT license) to ensure legacy usage
- new Boolean props: `fas`, `far`, `fal` and `fab` for v5 icon sets (if none provided then `fas`), or we could make them more semantic as discussed in #63

@danawoodman What's your opinion?

**Comment by danawoodman** [comment]
@KagamiChan I'm always open to PRs. How do you plan on detecting FontAwesome v5 versus older versions? It would break if you changed from `fa` to `fas`, for example for all existing users of `react-fontawesome`. 

One less than ideal option would be to include `fa` as well as `fas|far|fal|fab` eg `fa fas fa-rocket`.

Can you let me know how you're planning on approaching this before you jump off and work on it?

**Comment by KagamiChan** [comment]
Good question, I was considering it as a breaking change. 

v5 is divided into different sets and many icon name has changed, which introduced name collisions. So if we're planning to support both v4 and v5 css, without a flag the result could be unexpected.

Example: `glass` in v4 has been renamed to `glass-martini`
`<FA name="glass" />` could render:
```html
<span class="fa fas fa-glass fa-glass-martini" />
```
for v4 css, `fa` and `fa-glass` will take effect, and for v5 css, `fa`, `fas` and `fa-glass-martini` will match the selectors. That's OK.

However, `google-plus` in v4 is moved to `fab` and renamed `google-plus-g`
in the same way `<FA name="google-plus" />` could render:
```html
<span class="fa fab fa-google-plus fa-google-plus-g" />
```
However in v5 `fab` provides another `google-plus` icon, the result is a little tricky.

So my proposal is: 
- `legacy` or `v4` or `fa` for v4 usage with v4 css
- `fas|far|fal|fab` for v5 usage with v5 css. 
- If none provided, we treat it as v4 usage with v5 css file and then perform the shim

**Comment by danawoodman** [comment]
Going to close for now. Feel free to convince me I'm wrong though! 😄

**Comment by KagamiChan** [comment]
Really appreciate your detail explanation and I understand your concerns.

I'll try to make out a less painful way to migrate with official packages, and append my findings if they worth noting down.

**Comment by twig-openlearning** [comment]
@danawoodman thanks for the informative responses. would be a good idea to put that in the README to avoid more of these issues being created

**Comment by danawoodman** [comment]
@KagamiChan @twig-openlearning I have added a note about using the official component in the readme 🕺
