### ISSUE TITLE
No title prop

### ISSUE THREAD

**Issue by camloken** [danawoodman/react-fontawesome#70]
Sometimes it's helpful to put title's on icons to provide helpful tips on hover. I just realized react-fontawesome doesn't support the title attribute.

**Comment by danawoodman** [comment]
Actually, it does since we just pass any unknown props to the component. Give it a shot and if it doesn't work, reopen!

**Comment by camloken** [comment]
Actually, the title attribute is not supported on SVG elements in Chrome. You're right, the title attribute is rendered in the DOM, but chrome doesn't do anything with it, so you can't see it.

**Comment by danawoodman** [comment]
I’m confused. You’re mentioning SVG but this library doesn’t support the new FA SVG icons. Are you sure you’re not confusing this library with the official FA React Component?

**Comment by camloken** [comment]
My apologies, I was confused this with the fortawesome/react-fontawesome repo.

**Comment by danawoodman** [comment]
Haha, no worries, that's what I thought 😉 

Have a good weekend 🕺
