### ISSUE TITLE
Title prop would be extremely useful

### ISSUE THREAD

**Issue by henkkah** [danawoodman/react-fontawesome#74]
ie. for having a description for a warning or error etc.

Using a wrapper for the title prop sure works but it's not very elegant and produces unnecessary clutter.

**Comment by danawoodman** [comment]
You can pass in any prop you want. Try:

```jsx
<FA name=“rocket” title=“Rocket go vroom!” />
```

**Comment by henkkah** [comment]
Sorry, go this mixed up with the [Font Awesome 5 component](https://github.com/FortAwesome/react-fontawesome)...
