### ISSUE TITLE
Cant use brands

### ISSUE THREAD

**Issue by lukepighetti** [danawoodman/react-fontawesome#75]
`<FontAwesome name="react"/>` no longer appears to work

it uses class `fa fa-react` when in Font Awesome 5 it should be `fab fab-react`

**Comment by danawoodman** [comment]
Please use the official Font Awesome React component if you are using FA v5. Cheers 🍺

**Comment by lukepighetti** [comment]
I didn't even know there was one. :) thanks

**Comment by danawoodman** [comment]
@lukepighetti yeah they added it with v5 so this component will eventually die 😉 💀
