### ISSUE TITLE
Mark repository as archived?

### ISSUE THREAD

**Issue by TomasHubelbauer** [danawoodman/react-fontawesome#83]
Hi, it seems this repository is no longer actively maintained. I'm judging this by the fact that the last publish to NPM was three years ago. That's absolutely fine, however, I would like to request that you either mark the repository as archived or add a notice to the README on GitHub and NPM, as that would help people realize immediately. I only noticed after some icons from FA 5 I was using were not available. I have switched to https://github.com/FortAwesome/react-fontawesome which you could point people to as an alternative which is actively maintained.

**Comment by danawoodman** [comment]
@TomasHubelbauer yes, archiving is an option which I will consider, though that would mean that there would be no ability for people to submit bugs or PRs. If there was, for example a security vulnerability, I would not be able to easily be notified of it or resolve it.

I do make a pretty clear message at the top of the readme about FA5:

> If you are using Font Awesome v5+, please use the official React component!. react-fontawesome does not support FontAwesome v5!

If you think that message could be more clear, please feel free to submit a PR and I will be happy to update it.

**Comment by danawoodman** [comment]
That all said, I did neglect to push up some of the latest changes so I have pushed up a new release `v1.7.1` that includes some minor changes. Thanks for the reminder that I neglected `npm publish` 🤦‍♂

**Comment by TomasHubelbauer** [comment]
Thanks! Honestly I never saw that message due to my banner blindness, but now I think it is clear enough.
