### ISSUE TITLE
Can't get "-o" icon names to render

### ISSUE THREAD

**Issue by miki-nis** [danawoodman/react-fontawesome#91]
I've tried to use icons like in your example but those with "-o" suffix don't show. The base names, without "-o" work fine, however.

I've tried:
```
<FontAwesome name="clock-o" /> 
<FontAwesome name='square-o' stack='2x' />
```

When I visit list of fontawesome icons on their site, there are no alternatives for "-o" suffix. They implement icon variants using classes:
fas (solid icon)
far (regular outlined icon)
fal (light outline)

How do I achieve that with react-fontawesome?

**Comment by danawoodman** [comment]
@mickyinba you are using FontAwesome 4 not 5 correct? If you are using FA 5, please see note in readme about using official FontAwesome components instead, this repo only supports FA 4.

That said, the [clock-o](https://fontawesome.com/v4.7.0/icon/clock-o) and other 4.x icons should work assuming you are using the proper version of the FontAwesome font.

If you think this is an issue with FA 4 + react-fontawesome, please reopen!
